### ISSUE TITLE
这是啥原因？用不了啊

### ISSUE THREAD

**Issue by BrainWilliam** [xaboy/laravel-form-builder#1]
[InvalidArgumentException]                                                                      
  Could not find a version of package xaboy/laravel-form-builder matching your minimum-stability (stable). Require it
   with an explicit version constraint allowing its desired stability.

**Comment by BrainWilliam** [comment]
5.4和5.5还有5.6版本的都用不了

**Comment by xaboy** [comment]
奇怪,我检查一下

**Comment by xaboy** [comment]
我这边测试都好着呀,是不是你的composer使用的镜像有问题?

**Comment by BrainWilliam** [comment]
composer用的是中国镜像啊，应该没有问题吧，我试了还是不行

**Comment by xaboy** [comment]
你试试这个看行不行 https://packagist.laravel-china.org

**Comment by BrainWilliam** [comment]
换了镜像就可以用了！谢谢！

**Comment by xaboy** [comment]
😊
