### ISSUE TITLE
页面无法打开JS错误

### ISSUE THREAD

**Issue by robinhoo1973** [xaboy/laravel-form-builder#2]
拷贝代码,运行出现错误

Uncaught SyntaxError: Invalid or unexpected token iview.min.js:25

**Comment by xaboy** [comment]
这个错误好像是CDN加载出问题了，建议将依赖的 js 下载到本地

**Comment by robinhoo1973** [comment]
看了一下代码,是因为/form-builder类引用的是cdn的脚本,但是laravel-form-builder理由定义本地脚本和view都没用上,希望可以休整一下,谢谢

**Comment by xaboy** [comment]
好的,感谢您的反馈.我会在下个版本中修复

**Comment by xaboy** [comment]
感谢您的建议,我已在1.2.1版本中调整
