### ISSUE TITLE
如何与iview版form-create配合使用？

### ISSUE THREAD

**Issue by lonycn** [xaboy/laravel-form-builder#3]
只有view()方法渲染页面，不能够返回json格式给前端？

**Comment by xaboy** [comment]
$form->getRules()就可以获取到生成规则. 
可以参考:
[获取生成规则](https://github.com/xaboy/laravel-form-builder/blob/master/src/views/script.blade.php#L10)
[通过 form-create生成表单](https://github.com/xaboy/laravel-form-builder/blob/master/src/assets/form-create/form-builder.js#L2)
