### ISSUE TITLE
laravel专用表单生成器示例

### ISSUE THREAD

**Issue by lirunsheng** [xaboy/laravel-form-builder#9]
我使用了laravel专用的的表单生成器后，没有示例，有一些地方使用的不是很清楚，系统能够出一个laravel生成的示例

**Comment by xaboy** [comment]
如果是前后端分离的,推荐使用 [form-builder](https://github.com/xaboy/form-builder). 这个项目已经没有在更新了

**Comment by lirunsheng** [comment]
感谢大神，查看了crmeb项目源码后，对from-builder的使用有了更高的认识了，目前也是使用前后端项结合的方式

**Comment by xaboy** [comment]
感谢支持, form-builder 目前在处理异步数据和事件方面还是有点复杂度,需要前端有一些配合
